name: Build

on:
  push:
    branches:
      - "main"
      - "main-lts"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:
    name: Build - RESTEasy Classic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
#          windows-latest - Disabled due to https://github.com/quarkiverse/quarkus-openapi-generator/pull/836#issuecomment-2457329495
        ]
        java: [
          { 'version': '17' },
          { 'version': '21' }
        ]
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v4
      - name: Set up JDK  ${{matrix.java.version}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: 'maven'

      - name: Build with Maven
        run: mvn '-Dorg.slf4j.simpleLogger.log.org.openapitools=off' -B formatter:validate impsort:check verify --file pom.xml

  build_reactive:
    name: Build - RESTEasy Reactive
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
#          windows-latest - Disabled due to https://github.com/quarkiverse/quarkus-openapi-generator/pull/836#issuecomment-2457329495
        ]
        java: [
          { 'version': '17' },
          { 'version': '21' }
        ]
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java.version}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -Presteasy-reactive '-Dorg.slf4j.simpleLogger.log.org.openapitools=off' -B formatter:validate impsort:check verify --file pom.xml
