name: Label New PRs

on:
  pull_request_target:
    types: [opened]

permissions:  
  issues: write
  pull-requests: write

jobs:
  add_label:
    name: Add backport-main-lts label
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.ref == 'main' &&
      !contains(
        fromJson('["dependabot[bot]", "dependabot-preview[bot]"]'),
        github.actor
      )
    steps:
      - name: Add backport-main-lts label
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            console.log(`Adding label backport-main-lts to ${owner}/${repo}#${issue_number}`);

            const res = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['backport-main-lts']
            });

            console.log(`addLabels status: ${res.status}`);
